#ifndef RANDOMNUMBERGENERATOR1_GLOBAL_H
#define RANDOMNUMBERGENERATOR1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RANDOMNUMBERGENERATOR1_LIBRARY)
#  define RANDOMNUMBERGENERATOR1_EXPORT Q_DECL_EXPORT
#else
#  define RANDOMNUMBERGENERATOR1_EXPORT Q_DECL_IMPORT
#endif

#endif // RANDOMNUMBERGENERATOR1_GLOBAL_H
