#ifndef DLLKOTITEHTAVA1_GLOBAL_H
#define DLLKOTITEHTAVA1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLKOTITEHTAVA1_LIBRARY)
#  define DLLKOTITEHTAVA1_EXPORT Q_DECL_EXPORT
#else
#  define DLLKOTITEHTAVA1_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLKOTITEHTAVA1_GLOBAL_H
