#ifndef DLLKOTITEHTAVA1JATKO_GLOBAL_H
#define DLLKOTITEHTAVA1JATKO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLKOTITEHTAVA1JATKO_LIBRARY)
#  define DLLKOTITEHTAVA1JATKO_EXPORT Q_DECL_EXPORT
#else
#  define DLLKOTITEHTAVA1JATKO_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLKOTITEHTAVA1JATKO_GLOBAL_H
